#include "LEDCfg.h"
#include "../../MCAL/GPIO/GPIO.h"




 LED_t LEDS[LEDs_NUM]=
{
    {GPIO_PORTC,GPIO_PIN13,LED_REVERSE,LED_OFF},
    {GPIO_PORTA,GPIO_PIN1,LED_FORWARD,LED_ON},
    {GPIO_PORTA,GPIO_PIN2,LED_REVERSE,LED_ON},
    {GPIO_PORTA,GPIO_PIN3,LED_REVERSE,LED_OFF}
};